- name: Install acmetool
  xbps:
    name: acmetool

- name: Update acme defaults
  template:
    src: templates/acme/reload.conf
    dest: /etc/default/acme-reload

- name: Update acme reload hook
  template:
    src: templates/acme/reload.hook
    dest: /usr/libexec/acme/hooks/reload
    mode: '0755'

- name: Update acme haproxy hook
  template:
    src: templates/acme/haproxy.hook
    dest: /usr/libexec/acme/hooks/haproxy
    mode: '0755'

- name: Install cronie
  xbps:
    name: cronie

- name: Enable cronie
  runit:
    name: cronie
    enabled: yes

- name: Add acme cronjob
  cron:
    name: "refresh certs"
    job: "/sbin/acmetool --batch reconcile 2>&1"
    minute: '35'
    hour: '12'
