- name: Install nftables
  xbps:
    name: nftables

- name: Remove iptables
  xbps:
    name: iptables
    state: present

- name: Update nftables rules
  template:
    src: templates/nftables.conf
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0600'
  notify:
    - restart nftables

- name: Enable nftables
  runit:
    name: nftables
    enabled: yes
  notify:
    - restart nftables
